site_name: Mozmeao Platforms Documentation
site_url: https://mozmeao.github.io/platform-docs/

copyright: "Â© Copyright 2011-2025, Mozilla"
dev_addr: 127.0.0.1:8765  # Default :8000 is used by the devserver of the apps

repo_name: 'mozmeao/platform-docs'
repo_url: 'https://github.com/mozmeao/platform-docs'
edit_uri: edit/main/docs/

plugins:
  - search

theme:
  name: material
  logo: images/mozilla-logo.svg
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: material/lightbulb
      bedrock: material/alpha-b-box
      springfield: material/alpha-s-box
      both: material/set-all
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - abbr
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - js/project-tabs.js

extra_css:
  - css/project-tabs.css

nav:
  - Home: index.md

  - Getting Started:
    - Getting Started: getting-started/index.md
    - Installation: getting-started/install.md
    - Running Locally: getting-started/running-locally.md
    - Contributing: getting-started/contributing.md

  - Development:
    - Development: development/index.md
    - Coding Style: development/coding-style.md
    - Browser Support: development/browser-support.md
    - Adding a View: development/views.md
    - Finding Templates: development/finding-templates.md
    - Writing JavaScript: development/javascript.md
    - Writing CSS: development/protocol.md
    - Working with Images: development/images.md
    - Asset Bundling: development/assets.md
    - Redirects: development/redirects.md
    - Banners: development/banners.md
    - Feature Switches: development/feature-switches.md
    - Managing Dependencies: development/dependencies.md

  - Testing:
    - Testing: testing/index.md
    - Pytest (Python): testing/pytest.md
    - Jasmine (JavaScript): testing/jasmine.md
    - Playwright (Integration): testing/playwright.md
    - Axe (Accessibility): testing/axe.md
    - Selenium (Legacy): testing/selenium.md

  - Code Review:
    - Code Review: code-review/index.md
    - Checklists: 
      - Checklists: code-review/checklists/index.md
      - General: code-review/checklists/general.md
      - Analytics: code-review/checklists/analytics.md
      - CSS: code-review/checklists/css.md
      - Experiments: code-review/checklists/experiments.md
      - HTML: code-review/checklists/html.md
      - JavaScript: code-review/checklists/js.md
      - Localization: code-review/checklists/l10n.md
      - Media: code-review/checklists/media.md
      - Tests: code-review/checklists/tests.md

  - Localization:
    - Localization: l10n/index.md
    - Fluent Basics: l10n/fluent.md
    - Fluent Configuration: l10n/configuration.md
    - CSS & Fonts: l10n/css.md

  - Measurement:
    - Measurement: measurement/index.md
    - Consent Management: measurement/consent-management.md
    - Website Analytics: measurement/analytics.md
    - Firefox Desktop Attribution: measurement/firefox-desktop.md
    - Firefox Mobile Attribution: measurement/firefox-mobile.md
    - Mozilla Accounts Attribution: measurement/mozilla-accounts.md
    - A/B Testing: measurement/abtest.md
    - Markus: measurement/markus.md

  - Firefox Downloads:
    - firefox-downloads/download-buttons.md
    - firefox-downloads/desktop-download-support.md
    - firefox-downloads/desktop-download-pages.md
    - firefox-downloads/desktop-download-as-default.md

  - Integrations:
    - Integrations: integrations/index.md
    - UI Tour: integrations/uitour.md
    - Mozilla Account Helpers: integrations/mozilla-accounts.md
    - VPN Subscriptions: integrations/vpn-subscriptions.md
    - Newsletters: integrations/newsletters.md
    - Send to Device: integrations/send-to-device.md
    - Legal Docs: integrations/legal-docs.md
    - Release Notes: integrations/release-notes.md

  - Wagtail CMS:
    - Wagtail CMS: cms/index.md
    - Local Setup: cms/setup.md
    - Creating Pages: cms/pages.md
    - Images: cms/images.md
    - Localization: cms/l10n.md

  - Operations:
    - Operations: operations/index.md
    - CI/CD Pipeline: operations/pipeline.md
    - Demo Servers: operations/demos.md
    - Databases: operations/databases.md
    - Database Migrations: development/migrations.md
    - Sitemaps: operations/sitemap.md
    - Task Queue: operations/task-queue.md
    - Private Repos: operations/private-repos.md

  - Reference:
    
    - Architectural Decisions:
      - architecture/decisions/index.md
      - 1. Record architecture decisions: architecture/decisions/0001-record-architecture-decisions.md
      - 2. Move CI/CD Pipelines to Gitlab: architecture/decisions/0002-move-ci-cd-pipelines-to-gitlab.md
      - 3. Use Cloudflare Workers and Convert for multi-variant testing: architecture/decisions/0003-use-cloudflare-workers-and-convert-for-multi-variant-testing.md
      - 4. Use Fluent For Localization: architecture/decisions/0004-use-fluent-for-localization.md
      - 5. Use a Single Docker Image For All Deployments: architecture/decisions/0005-use-a-single-docker-image-for-all-deployments.md
      - 6. Revise tooling for Python dependency management: architecture/decisions/0006-revise-tooling-for-python-dependency-management.md
      - 7. Further revise tooling for Python dependency management: architecture/decisions/0007-further-revise-tooling-for-python-dependency-management.md
      - 8. Move Demos To GCP: architecture/decisions/0008-move-demos-to-gcp.md
      - 9. Manage Contentful schema state via migrations: architecture/decisions/0009-use-manage-contentful-migrations.md
      - 10. Move CI to Github Actions for Unit and Integration tests: architecture/decisions/0010-move-ci-cd-to-github-actions.md
      - 11. Use StatsD for metrics collection: architecture/decisions/0011-use-statsd-for-metrics-collection.md
      - 12. Use Wagtail CMS: architecture/decisions/0012-wagtail-for-cms.md
    - Contentful (deprecated): reference/contentful.md
    - External Content Cards (deprecated): reference/content-cards.md

extra:
  social:
    - icon: fontawesome/solid/bug
      link: https://github.com/mozmeao/platform-docs/
      name: Report a problem with this documentation
